#!/bin/bash
#SBATCH --account=c24
#SBATCH --time=00:10:00
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --gres=gpu:1
#SBATCH --hint=nomultithread
#SBATCH --constraint=gpu
#SBATCH --partition=debug
#SBATCH --exclusive

module load daint-gpu
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export NCCL_DEBUG=INFO
export NCCL_IB_HCA=ipogif0
export NCCL_IB_CUDA_SUPPORT=1

RUNPATH=/scratch/snx3000/scruzale/ML_APTS/
cd $RUNPATH || exit

# Retrieve parameters from the command line
optimizer=$1
dataset=$2
batch_size=$3
model=$4
num_subdomains=$5
num_replicas_per_subdomain=$6
num_stages_per_replica=$7
trial=$8
epochs=$9

# Display parameters (for debugging)
echo "Optimizer: $optimizer"
echo "Dataset: $dataset"
echo "Batch size: $batch_size"
echo "Model: $model"
echo "Number of subdomains: $num_subdomains"
echo "Number of replicas per subdomain: $num_replicas_per_subdomain"

echo "Activating llms $(date)"
source activate llms
echo "Calling python script $(date)"
srun python3 -u tests/scaling_test.py --optimizer "$optimizer" --dataset "$dataset" --batch_size "$batch_size" --model "$model" --num_subdomains "$num_subdomains" --num_replicas_per_subdomain "$num_replicas_per_subdomain" --num_stages_per_replica "$num_stages_per_replica" --trial "$trial" --epochs "$epochs"
