#!/bin/bash
#SBATCH --account=c24
#SBATCH --time=00:30:00
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --gres=gpu:1
#SBATCH --hint=nomultithread
#SBATCH --constraint=gpu
#SBATCH --partition=debug
#SBATCH --exclusive

module load daint-gpu

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export NCCL_DEBUG=INFO
export NCCL_IB_HCA=ipogif0
export NCCL_IB_CUDA_SUPPORT=1

RUNPATH=/scratch/snx3000/scruzale/ML_APTS/
cd $RUNPATH || exit

# Retrieve parameters from the command line
optimizer=$1
batch_size=$2
learning_rate=$3
trial_number=$4
epochs=$5
dataset=$6

# Display parameters (for debugging)
echo "Optimizer: $optimizer"
echo "Batch size: $batch_size"
echo "Learning rate: $learning_rate"
echo "Trial number: $trial_number"
echo "Epochs: $epochs"
echo "Dataset: $dataset"

echo "Activating llms $(date)"
source activate llms
echo "Calling python script $(date)"
srun python3 -u src/parallel_test.py --optimizer "$optimizer" --batch_size "$batch_size" --lr "$learning_rate" --trial_number "$trial_number" --epochs "$epochs" --dataset "$dataset"
echo "Test done $(date)"
