#!/bin/bash
# SLURM script for Piz Daint

#SBATCH --time=00:30:00
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --hint=nomultithread
#SBATCH --constraint=gpu
#SBATCH --account=c24
#SBATCH --partition=normal
#SBATCH --exclusive

echo "Running apts_w.job..."

module load daint-gpu

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export NCCL_DEBUG=INFO
export NCCL_IB_HCA=ipogif0
export NCCL_IB_CUDA_SUPPORT=1

RUNPATH=/scratch/snx3000/scruzale/ML_APTS/
cd $RUNPATH || exit

# Iterate over all passed arguments
for arg in "$@"; do
    IFS='=' read -r key value <<< "$arg"
    case $key in
        --nr_models)
            nr_models="$value"
            ;;
        --minibatch_size)
            minibatch_size="$value"
            ;;
        *)
            echo "Unknown argument: $key"
            exit 1
            ;;
    esac
done

ARGS="--nr_models $nr_models --minibatch_size $minibatch_size"
echo "ARGS for python file: $ARGS"

echo "Activating llms `date`"
source activate llms
echo "Calling python script `date`"
srun python3 -u ./src/main_APTS_ResNET.py $ARGS;
echo "All done $(date)"
